openapi: 3.0.0
info:
  version: '1.0'
  title: Empo News
  description: 'This is the Open API documentation for the REST API of **Empo News** deployed at <https://empo-news.herokuapp.com/>. <br>All operations are executable and require authentication. In this case, you must **Authorize** your request by providing the api_key vaule you got when you created the account.'
servers:
    - url: 'https://empo-news.herokuapp.com/api/v1'
paths:
    /profile:
       put:
            summary: Updates the current signed in user profile
            operationId: updateMyProfile
            tags:
                - users
            parameters:
                - in: query
                  name: parameter
                  required: true
                  schema:
                    type: object
                    properties:
                        about:
                            description: The new about
                            type: string
                            maxLength: 2000
                            example: I love crisps.
                        showdead:
                            description: The new showdead
                            type: boolean
                            example: false
                        noprocast:
                            description: The new noprocast
                            type: boolean
                            example: true
                        maxvisit:
                            description: The new maxvisit
                            type: integer
                            format: int32
                            example: 20
                        minaway:
                            description: The new minaway
                            type: integer
                            format: int32
                            example: 30
                        delay:
                            description: The new delay
                            type: integer
                            format: int32
                            example: 20
                    minProperties: 1
                    additionalProperties: false
                  style: form
                  explode: true
            responses:
                200:
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MyProfile'
                400:
                    $ref: '#/components/responses/400'
                401:
                    $ref: '#/components/responses/401'
                403:
                    $ref: '#/components/responses/403'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
    /profile/{username}:
        get:
            summary: Returns a user profile
            operationId: getUserProfile
            tags:
                - users
            parameters:
                - $ref: '#/components/parameters/userId'
            responses:
                200:
                    $ref: '#/components/responses/profileResponse'
                401:
                    $ref: '#/components/responses/401'
                403:
                    $ref: '#/components/responses/403'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
    /contributions:
        post:
            summary: Adds a new contribution
            operationId: createContribution
            tags:
                - contributions
            description: >
                Adds a new contribution to the system. When publishing a contribution with url, if another one already has the same url it won't create a new one and will return the existent one.
            requestBody:
                description: Provide the content of the new contribution
                content:
                    application/json:
                        schema:
                            oneOf:
                                - $ref: '#/components/schemas/CreateContributionWithUrl'
                                - $ref: '#/components/schemas/CreateContributionWithText'
                        examples:
                            urlExample:
                                $ref: '#/components/examples/postUrl'
                            textExample:
                                $ref: '#/components/examples/postText'
                required: true
            responses:
                200:
                    description: A contribution with the same url already exists
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Contribution'
                201:
                    description: Contribution created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Contribution'
                400:
                    $ref: '#/components/responses/400'
                401:
                    $ref: '#/components/responses/401'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
        get:
            summary: Retrieves all the contributions
            operationId: listContributions
            description: >
                Retrieves all the contibutions according to the union of the filters. The result will be ordered according to the orderBy parameter if specified.
            tags:
                - contributions
            parameters:
              - $ref: '#/components/parameters/userIdQuery'
              - in: query
                name: filter
                description: >
                  Avaliable filters:
                    * `showEn` - Filter Show EN contributions
                    
                    * `url` - Filter contributions by their URL. It cannot be used in conjunction with ask parameter
                    
                    * `ask` - Filter all contributions with text. It cannot be used in conjunction with url parameter
                schema:
                    type: object
                    properties:
                      showEn:
                        type: boolean
                        enum:
                            - true
                      url:
                        type: string
                        format: url
                        example: 'https://www.google.es'
                      ask:
                        type: boolean
                        enum:
                            - true
                    minProperties: 1
                    additionalProperties: false
                style: form
                explode: true
              - $ref: '#/components/parameters/orderBy'
            responses:
                200:
                  description: List of all contributions
                  content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Contribution'
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    error:
                                        type: string
                                        example: Bad Request
                                    message:
                                        type: string
                                        example: Url and ask parameters cannot be used together
                401:
                     $ref: '#/components/responses/401'
                404:
                     $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                   $ref: '#/components/responses/500'
    /contribution/{id}:
        put:
            summary: Edits a contribution or comment by its ID
            operationId: editContributionById
            tags:
                - contributions
            description: Edits a single contribution or comment
            parameters:
                - in: path
                  name: id
                  description: ID of the contribution or comment
                  required: true
                  schema:
                      type: integer
                      format: int64
                - in: query
                  name: parameter
                  required: true
                  schema:
                    type: object
                    properties:
                        title:
                            description: The new title
                            type: string
                            minLength: 4
                            maxLength: 80
                            example: 'This is my new title'
                        text:
                            description: The new text. It must not be used in those contributions that have a url instead of text.
                            type: string
                            nullable: true
                            example: Hey there!
                    minProperties: 1
                    additionalProperties: false
                  style: form
                  explode: true
            responses:
                200:
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: '#/components/schemas/Contribution'
                                    - $ref: '#/components/schemas/Comment'
                            examples:
                                contributionExample:
                                    $ref: '#/components/examples/contributionExample'
                                commentExample:
                                    $ref: '#/components/examples/commentExample'
                400:
                    $ref: '#/components/responses/400'
                401:
                    $ref: '#/components/responses/401'
                403:
                    $ref: '#/components/responses/403'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
        get:
            summary: Finds a contribution by its ID
            operationId: getContributionById
            tags:
                - contributions
            description: Returns a single contribution
            parameters:
                - in: path
                  name: id
                  description: ID of the contribution
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                200:
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Contribution'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
        delete:
            summary: Deletes a contribution or comment by its ID
            operationId: deleteContribution
            tags:
                - contributions
            parameters:
                - in: path
                  name: id
                  description: ID of the contribution
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                204:
                    $ref: '#/components/responses/204'
                404:
                    $ref: '#/components/responses/404'
                401:
                    $ref: '#/components/responses/401'
                403:
                    $ref: '#/components/responses/403'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
    /contribution/{id}/vote:
        put:
            summary: Votes a contribution or comment
            operationId: voteContribution
            tags:
                - contributions
            parameters:
              - $ref: '#/components/parameters/contributionId'
            responses:
                204:
                    $ref: '#/components/responses/204'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                409:
                    $ref: '#/components/responses/409'
                500:
                    $ref: '#/components/responses/500'
    /contribution/{id}/unvote:
        put:
            summary: Unvotes a contribution or comment
            operationId: unvoteContribution
            tags:
                - contributions
            parameters:
              - $ref: '#/components/parameters/contributionId'
            responses:
                204:
                    $ref: '#/components/responses/204'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                409:
                    $ref: '#/components/responses/409'
                500:
                    $ref: '#/components/responses/500'
    /contribution/{id}/hide:
        put:
            summary: Hides a contribution or a comment
            operationId: hideContribution
            tags:
                - contributions
            parameters:
              - $ref: '#/components/parameters/contributionId'
            responses:
                204:
                    $ref: '#/components/responses/204'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                409:
                    $ref: '#/components/responses/409'
                500:
                    $ref: '#/components/responses/500'
    /contribution/{id}/unhide:
        put:
            summary: Unhides a contribution or a comment
            operationId: unhideContribution
            tags:
                - contributions
            parameters:
              - $ref: '#/components/parameters/contributionId'
            responses:
                204:
                    $ref: '#/components/responses/204'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                409:
                    $ref: '#/components/responses/409'
                500:
                    $ref: '#/components/responses/500'
    /contribution/{id}/comments:
        parameters:
                - $ref: '#/components/parameters/contributionId'
        post:
            summary: Creates a comment
            description: Creates a comment for the given contribution or comment.
            operationId: createComment
            tags:
              - comments
            requestBody:
                description: Provide the content of the new comment
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                text: 
                                    type: string
                                    example: What's up?
                required: true
            responses:
                201:
                    description: Comment created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Comment'
                400:
                    $ref: '#/components/responses/400'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                409:
                    description: 'Error: Conflict'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                errorExample:
                                    value:
                                      status: 409
                                      error: "Conflict"
                                      message: "The contribution is yours"
                500:
                    $ref: '#/components/responses/500'
        get:
            summary: Retrieves all comments
            description: Retrieves all comments for the given contribution or comment
            operationId: listContributionComments
            tags:
              - comments
            parameters:
                - $ref: '#/components/parameters/userIdQuery'
                - $ref: '#/components/parameters/commentOrderBy'
            responses:
                200:
                  description: List of all contribution comments
                  content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Comment'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                  $ref: '#/components/responses/500'
    /comments:
        get:
            summary: Retrieves all the comments
            operationId: listComments
            tags:
                - comments
            parameters:
              - $ref: '#/components/parameters/userIdQuery'
              - $ref: '#/components/parameters/commentOrderBy'
            responses:
                200:
                  description: List of all comments
                  content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Comment'
                401:
                     $ref: '#/components/responses/401'
                404:
                     $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                   $ref: '#/components/responses/500'
    /comment/{commentId}:
        get:
            summary: Gets a comment by its ID
            operationId: getCommentById
            tags:
              - comments
            parameters:
                - name: commentId
                  in: path
                  required: true
                  description: ID of the comment
                  schema:
                      type: integer
                      format: int64
            responses:
                200:
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Comment'
                401:
                    $ref: '#/components/responses/401'
                404:
                    $ref: '#/components/responses/404'
                405:
                    $ref: '#/components/responses/405'
                500:
                    $ref: '#/components/responses/500'
security:
- ApiKeyAuth: []
components:
    parameters:
        contributionId:
            name: id
            in: path
            required: true
            description: ID of the contribution or comment
            schema:
              type: integer
              format: int64
        userId:
            name: username
            in: path
            required: true
            description: Username of the user
            schema:
                type: string
                maxLength: 150
        userIdQuery:
            name: username
            in: query
            description: Filter by creator
            schema:
                type: string
                maxLength: 150
        orderBy:
            in: query
            name: orderBy
            description: >
                  Orders by:
                    * `publication_date_asc` - Orders by newest contribution
                    
                    * `publication_date_desc` - Orders by oldest contribution
                    
                    * `title_asc` - Orders by ascending title, from A to Z
                    
                    * `title_desc` - Orders by descending title, from Z to A
                    
                    * `votes_asc` - Orders by  ascending number of votes
                    
                    * `votes_desc` - Orders by  descending number of votes
            schema:
                type: string
                enum:
                    - publication_date_asc
                    - publication_date_desc
                    - title_asc
                    - title_desc
                    - votes_asc
                    - votes_desc
        commentOrderBy:
              in: query
              name: orderBy
              description: >
                  Orders by:
                    * `publication_date_asc` - Orders by newest contribution
                    
                    * `publication_date_desc` - Orders by oldest contribution
                    
                    * `votes_asc` - Orders by  ascending number of votes
                    
                    * `votes_desc` - Orders by  descending number of votes
              schema:
                  type: string
                  enum:
                      - publication_date_asc
                      - publication_date_desc
                      - votes_asc
                      - votes_desc
    responses:
        profileResponse:
            description: Returns a user profile
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/BasicResponse'
                    examples:
                        myProfileExample:
                            $ref: '#/components/examples/myProfile'
                        otherProfileExample:
                            $ref: '#/components/examples/otherProfile'
        200:
            description: Successful operation
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/BasicResponse'
                    examples:
                        successExample:
                            $ref: '#/components/examples/success200'
        201:
            description: Successful operation
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/BasicResponse'
                    examples:
                        successExample:
                            $ref: '#/components/examples/success201'
        204:
            description: Successful operation
        400:
            description: 'Error: Bad Request'
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error400'
        401:
            description: 'Error: Unauthorized'
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error401'
        403:
            description: 'Error: Forbidden'
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error403'
        404:
            description: 'Error: Not Found'
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error404'
        405:
            description: Method Not Allowed
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/BasicResponse'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error405'
        409:
            description: 'Error: Conflict'
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error409'
        500:
            description: 'Error: Internal server error'
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        errorExample:
                            $ref: '#/components/examples/error500'
    schemas:
        MyProfile:
            type: object
            properties:
                username:
                    type: string
                    maxLength: 150
                    example: John
                date_joined:
                    type: string
                    format: date-time
                    example: '2020-04-16 22:41:09.025719'
                karma:
                    type: integer
                    format: int32
                    default: 1
                    example: 4
                about:
                    type: string
                    maxLength: 2000
                    nullable: true
                    default: null
                    example: Hello my name is John and I love Empo News
                email:
                    type: string
                    format: email
                    maxLength: 254
                    example: john.doe@mail.com
                showdead:
                    type: boolean
                    default: false
                    example: true
                noprocast:
                    type: boolean
                    default: false
                    example: false
                maxvisit:
                    type: integer
                    format: int32
                    default: 1
                    example: 20
                minaway:
                    type: integer
                    format: int32
                    default: 100
                    example: 180
                delay:
                    type: integer
                    format: int32
                    default: 0
                    example: 0
        Contribution:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 1
                title:
                    type: string
                    minLength: 4
                    maxLength: 80
                    example: 'This is my first contribution'
                points:
                    type: integer
                    format: int32
                    default: 1
                    example: 3
                publication_time:
                    type: string
                    format: date-time
                    example: '2020-04-16 22:18:21.208736'
                url:
                    type: string
                    nullable: true
                    format: url
                    maxLength: 500
                    example: 'https://www.google.com'
                text:
                    type: string
                    nullable: true
                    example:
                comments:
                    type: integer
                    format: int32
                    default: 0
                    example: 3
                user_id:
                    type: string
                    maxLength: 150
                    example: John
                hidden:
                    type: integer
                    format: int32
                    example: 5
                liked:
                    type: boolean
                    example: true
                show:
                    type: boolean
                    example: true
        Comment:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 1
                points:
                    type: integer
                    format: int32
                    default: 1
                    example: 1
                publication_time:
                    type: string
                    format: date-time
                    example: '2020-04-16 22:18:21.208736'
                text:
                    type: string
                    nullable: true
                    example: What's up?
                comments:
                    type: integer
                    format: int32
                    default: 0
                    example: 0
                user_id:
                    type: string
                    maxLength: 150
                    example: John
                hidden:
                    type: integer
                    format: int32
                    default: 0
                    example: 0
                liked:
                    type: boolean
                    example: true
                show:
                    type: boolean
                    example: true
                contribution_id:
                    type: integer
                    format: int64
                    example: 235
                parent_id:
                    type: integer
                    format: int64
                    nullable: true
                    example: 381
        CreateContributionWithUrl:
            required:
            - title
            - url
            type: object
            properties:
                title:
                    type: string
                    minLength: 4
                    maxLength: 80
                    example: This is my first contribution
                url:
                    type: string
                    nullable: true
                    format: url
                    maxLength: 500
                    example: https://www.google.com
        CreateContributionWithText:
            required:
            - title
            - text
            type: object
            properties:
                title:
                    type: string
                    minLength: 4
                    maxLength: 80
                    example: This is my first contribution
                text:
                    type: string
                    nullable: true
                    example: Hello Wordl!
        BasicResponse:
            type: object
            properties:
                status:
                    type: integer
                    enum: [200, 201, 204]
                message: 
                    type: string
                
        Error:
            type: object
            properties:
                status:
                    type: integer
                    enum: [400, 401, 403, 404, 405, 409, 500]
                error: 
                    type: string
                    enum: ["Bad Request", "Unauthorized", "Forbidden", "Not Found", "Conflict", "Internal Server Error"]
                message: 
                    type: string
    examples:
        success200:
            value:
                status: 200
                message: OK
        success201:
            value:
                status: 201
                message: Created
        success204:
            value:
                status: 204
                message: Deleted
        error400:
            value:
                status: 400
                error: "Bad Request"
                message: "Content is too long (maximum is 80 characters)"
        error401:
            value:
                status: 401
                error: "Unauthorized"
                message: "You provided no api key (Api-Key Header)"
        error403:
            value:
                status: 403
                error: "Forbidden"
                message: "Your api key (Api-Key Header) is not valid"
        error404:
            value:
                status: 404
                error: "Not Found"
                message: "No item with that ID"
        error405:
            value:
                status: 405
                error: "Method not allowed"
                message: "The requested method is not allowed"
        error409:
            value:
                status: 409
                error: "Conflict"
                message: "The contribution already is in this state"
        error500:
            value:
                status: 500
                error: "Internal Server Error"
                message: "There was an error when retrieving the data"
        postUrl:
            value: 
                title: This is my first contribution
                url: https://www.google.com
        postText:
            value:
                title: This is my first contribution
                text: Hello World!
        myProfile:
            value:
                username: John
                date_joined: '2020-04-16 22:41:09.025719'
                karma: 3
                about: null
                email: john@mail.com
                showdead: false
                noprocast: false
                maxvisit: 1
                minaway: 100
                delay: 0
        otherProfile:
            value:
                username: Thomas
                date_joined: '2020-04-6 12:21:09.025719'
                karma: 7
        contributionExample:
            value:
                id: 1
                title: This is my new title
                points: 3
                publication_time: '2020-04-16 22:18:21.208736'
                text: Hey there!
                comments: 3
                user_id: John
                hidden: 5
                liked: true
                show: true
        commentExample:
            value:
                id: 1
                points: 1
                publication_time: '2020-04-16 22:18:21.208736'
                text: Hey there!
                comments: 2
                user_id: John
                hidden: 0
                liked: true
                show: true
                contribution_id: 235
                parent_id: 381
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            name: Api-Key
            in: header